### ISSUE TITLE
Metal/DX12 enabled on non-X system when using Nannou in a workspace

### ISSUE THREAD

**Issue by AngelOnFira** [nannou-org/nannou#827]
I was trying to use Nannou in a Rust workspace today, and as soon as I got the code refactored, `wgpu-hal` started throwing errors:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/14791619/147043216-7c295e05-05ba-40c1-b5c2-f776c7ae5220.png">

I want to use Nannou as a single crate in a monorepo workspace since I'm visualizing some stuff from another workspace member.

Here is a minimal repro. I set up everything in the same way as I have it in my other project, and whether it's run on Windows/Mac/Linux, it should throw the same error.

https://github.com/AngelOnFira/nannou-workspace-problem

**Comment by danwilhelm** [comment]
In your Cargo.toml, within a `[package]` section either set `resolver = "2"` or `edition = "2021" ` (which uses resolver 2 by default). WebGPU requires this to resolve which backend to use.

**Comment by AngelOnFira** [comment]
Do you mean in the root `cargo.toml`? I didn't think a package section went there, since it then required I add a `[[bin]]` section.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/14791619/147046451-e01af1f5-c08c-47a6-ba68-b2bf142f1ff4.png">

I gave this a go;

```toml
[package]
name="nannou-workspace"
edition = "2021"
version = "0.1.0"

[[bin]]
name="visualize"
path="nannou-test/src/main.rs"

[workspace]
members = [
    "nannou-test"
]
```

But it seems that it doesn't read the cargo.toml that's beside it, and can't find Nannou.

---

I think I've resolved it by just creating an empty `src/main.rs` at the root, but it feels like there should be a cleaner way to handle it. Oh well.
